name: Deploy Frontend - Prod
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@7b2cc9ff738d95ff2c8e4030db15b8c48ebb1ea1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          interval: 30

  build-deploy:
    needs: [consecutiveness]
    uses: Rukkor/geometra-antd/.github/workflows/deploy.yml@master
    with:
      environment: prod
      cloudfront_id: E3QH12Q1L53FUL
      locize_project_id: 3e82a4db-f62c-451e-948f-8951b6bd86ff
      locize_api_key: 3e73a957-5bc9-4274-ac7c-26bd8d4e31aa
      react_app_version: 2020-02-dev
      serverless_socket_url: wss://ws-sls.api.geometra.rukkor.io
      react_app_node_url: https://api.geometra.rukkor.io
      node_socket_reconnection_delay: 2000
      node_socket_reconnection_delay_max: 10000
      ifc_conversion_bucket_url: https://rukkor-bimerconverter-out-prod.s3.amazonaws.com/
      storage_bucket_url: https://geometra3.s3.eu-west-1.amazonaws.com/
      auth0_url: https://rest-sls.api.geometra.rukkor.io/
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      gh_pat: ${{ secrets.GH_PAT }}

  trigger-backend-deployment:
    needs: [build-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke backend deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy Backend - Prod
          repo: Rukkor/geometra-server
          ref: master
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "tag": "${{ github.event.release.tag_name }}"}'

  create-backup:
    needs: [build-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Copy deployed website to backup bucket # warning: this will overwrite if tag already exists
        run: aws s3 sync --delete --no-progress s3://geometra-4-host-prod s3://geometra-4-website-backup/${{ github.event.release.tag_name }}/
