name: Deploy Frontend - Dev
on:
  push:
    branches:
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    uses: Rukkor/geometra-antd/.github/workflows/deploy.yml@development
    with:
      environment: dev
      cloudfront_id: EYD3BAYMQJTJ6
      locize_project_id: 3e82a4db-f62c-451e-948f-8951b6bd86ff
      locize_api_key: 3e73a957-5bc9-4274-ac7c-26bd8d4e31aa
      react_app_version: 2020-02-dev
      serverless_socket_url: wss://dev-ws-sls.api.geometra.rukkor.io
      react_app_node_url: https://dev.api.geometra.rukkor.io
      node_socket_reconnection_delay: 2000
      node_socket_reconnection_delay_max: 10000
      ifc_conversion_bucket_url: https://rukkor-bimerconverter-out.s3.amazonaws.com/
      storage_bucket_url: https://geometra4-dev.s3.eu-west-1.amazonaws.com/
      auth0_url: https://dev-rest-sls.api.geometra.rukkor.io/
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  bundle-refresh:
    needs: [build-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Refresh
        run: curl https://dev.api.geometra.rukkor.io/frontendBundleRefresh?token=${{ secrets.FRONTEND_REFRESH_TOKEN }}
